version: "3.8"

services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/python/Dockerfile
    command: uwsgi --socket :8001 --module config.wsgi --py-autoreload 1 --logto /tmp/tmp.log
    env_file:
       - ./../.env.local
    volumes:
      - ./../:/workspace
    expose:
      - "8001"
    depends_on:
      - db
  db:
    build:
      context: ./
      dockerfile: ./mysql/Dockerfile
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: django_local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - django-db-store:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  web:
    image: nginx:1.23
    ports:
      - 8000:8000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    working_dir: /workspace
    depends_on:
      - app
  minio:
    image: quay.io/minio/minio:latest
    environment:
        MINIO_ROOT_USER: miniolocal
        MINIO_ROOT_PASSWORD: password
    command: ['minio', 'server', '/data', '--console-address', ':9001']
    ports:
        - "9000:9000"
        - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  django-db-store:
  minio-data:
