# Generated by Django 3.2.19 on 2023-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NationalPokedex",
            fields=[
                (
                    "id",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=12)),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.IntegerField()),
            ],
            options={
                "db_table": "national_pokedex",
                "managed": False,
            },
        ),
    ]
